name: Whiteforest
version: '${project.version}'
main: com.songro.whiteforest.Whiteforest
api-version: '1.19'
depend:
 - DiscordUtils
 - Citizens

permissions:
 teams.*:
  teams.sosumi: false
  teams.sodabean: false
  teams.hitullni: false
  teams.peace: false